version: "3.7"

services:
  node:
    image: "node:18.7-alpine3.16"
    container_name: $CONTAINER_NAME
    user: "node"
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    ports:
      - "$APP_PORT:1234"
    #command: npm install
    command: "npm run dev"
    #command: "npm run build"

 
